name: CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        shell: bash
        run: |
          echo "Building Docker Image"

  DeployPR:
    name: Deploy PR
    if: github.event_name == 'pull_request'
    environment:
      name: pull-request
      url: https://pr-${{ github.event.number }}.example.com
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy PR
        shell: bash
        run: |
          echo "Deploying PR"

  DeployStaging:
    name: Deploy Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.example.com
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Staging
        shell: bash
        run: |
          echo "Deploying Staging"

  DeployProduction:
    name: Deploy Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com
    runs-on: ubuntu-latest
    needs: [DeployStaging]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Production
        shell: bash
        run: |
          echo "Deploying Production"